<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">

    <!-- Include Common Properties -->
    <xacro:include filename="common_properties.xacro" />

    <!-- Include Gazebo Parameters -->
    <xacro:include filename="$(find robot_description)/urdf/robot_gazebo.xacro" />

    <!-- Include Ros2 Control Parameters -->
    <xacro:include filename="$(find robot_description)/urdf/robot_ros2_control.xacro" />

    <!-- Useful XACRO Variables (Properties) -->
    <xacro:property name="effort" value="30.0" />
    <xacro:property name="velocity" value="10.0" />

    <!-- Dimensions -->
    <xacro:property name="arm_base_length" value="0.15" />
    <xacro:property name="arm_base_height" value="0.03" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />

    <!-- Links -->
    <link name="world" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_length} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_length} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="1" l="${arm_base_length}" w="${arm_base_length}" h="${arm_base_height}"
                           xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="arm_link" params="prefix color">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${arm_length}"
                                    xyz="0 0 ${arm_length / 2.0}" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:arm_link prefix="forearm" color="black" />
    <xacro:arm_link prefix="hand" color="silver" />

    <!-- Joints -->
    <joint name="virtual_joint" type="fixed">
        <parent link="world" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="joint1" type="revolute">
        <parent link="base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-${PI}" upper="${PI}" effort="${effort}" velocity="${velocity}" />
    </joint>

    <joint name="joint2" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="-${PI / 2.0}" upper="${PI / 2.0}" effort="${effort}" velocity="${velocity}" />
    </joint>

</robot>
